AllCops:
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/puma.rb'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/**/*.rb'
    - 'bin/**/*'
  Rails: true
  DisplayCopNames: true
  StyleGuideCopsOnly: true

Metrics/LineLength:
  Max: 100